"use client"
import type { Metadata } from "next";
import { Inter, Poppins, Quicksand } from "next/font/google";
import Script from "next/script";
import SplashScreen from "./SplashScreen";
import "./globals.css";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import AnimatedTabs from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
  variable: '--font-poppins',
})
const quicksand = Quicksand({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-quicksand',
})




// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathName = usePathname()
  const isHome = pathName === "/"
  const [isLoading, setIsLoading] = useState(isHome)

  // useEffect(() => {
  //   if (isLoading) return
  // }, [isLoading])

  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="logo-test.png"
          type="image/png"
          sizes="png"
        />
      </head>
      <title>Abhyuday Shukla</title>
      <body className={`${inter.className} ${poppins.variable} ${quicksand.variable}`}>

        {isLoading && isHome ? (
          <SplashScreen finishLoading={() => setIsLoading(false)} />
        ) : (
          <>

            <div className="realbody relative h-full w-full">
              <AnimatedTabs />
              <div className="canvas-wrap z-0 fixed top-0 left-0 h-full w-full opacity-0">
                <canvas />
              </div>
              
              {children}

            </div>
            
            <Script src="/bg.js"></Script>

          </>
        )}
      </body>

    </html>
  );
}
